language: java
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip
  - unzip -qq apache-maven-3.5.4-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.4
  - export PATH=$M2_HOME/bin:$PATH
  - chmod +x travis-before.sh
  - sh travis-before.sh
deploy:
  file: target/*.jar
  provider: gcs
  access_key_id: GOOG3FSSUKMB7MIEMWONCXUO
  secret_access_key:
    secure: N2QQofmqNqQpF+5KaY18G8u3cNKpYGYNjzfpA77Si2LtIZWXLmgiC5GOOSbguzntck193AE3+s6O2B1sCJYpgs0n7t2Ur5G0lq7JZlDKl3aVSgbJouSkjgvdY3xn3VSMU3ISCsW5GQr5UXvJ6ACVfKLRJG8C/KEEuNKleK18Gyrb+CBK81IODe8p7ZfEVQ7mj/uLOfiS/S1v8ZhWwcIoA4Bj0EtYTS2B+VrkbUcMhS/Z0DRZaZK/srz/Hmu5JEucQJ6LPRaigsWK3zxy1CaT+x5dIrd1WKKVCarMtk7LMY1ZclqmFLcqayIHwvxYtFFQRc7EwqkcZJxKURcp7cu04gUW8Ga7OFusPMEZ5hsAWgwaVkzbBeNbmpv4DjDq2YKqUtJKhL7sOQro5MIcccnLz4qKMQLH2jp6M+ZoDuxYTovPfcAwPBsmmYLdc7jGPG38DoMXUVOeiqUG3x35ZhEMjcDMvUw8dt0umyvDoOpIReBlqDsn1qywCaPhJC/v7l/fOYbfZn5//dGcxqW7vvDSO9FXJGzoPC2fEUSTZapmnX/hkiBBHA0Ude1VjtoYHu6CR8ADVE8XNRlXg47KkJZoFGAE+qfC3HJvEHaCYov8CpbMjG0xM7GzVbwPreZ9fKk9qzOpzXCIQ4qhmlmOkOFqXiec2IvcdkYqG19YUSbegnY=
  bucket: mhospitality
  on:
    repo: sgioldasis/bigquery-etl-dataflow-sample
  skip_cleanup: true
