language: java
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip
  - unzip -qq apache-maven-3.5.4-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.4
  - export PATH=$M2_HOME/bin:$PATH
  - chmod +x travis-before.sh
  - sh travis-before.sh
after_success:
  - mkdir -p travis-etl
  - cp target/*.jar travis-etl
  - ls travis-etl
deploy:
  provider: gcs
  access_key_id: GOOG3FSSUKMB7MIEMWONCXUO
  secret_access_key:
    secure: ni+BKLfH1R5IcHMHPljTu0SBVVgrd1GJ7r0e9Pt4mWRelCl4Vm1zNzZf9/JpSaSuT8OCBxjaGITVU6kpOafypqz+DvNIezQ75HSLTa/8os2bpXeSWgTfoQVixa7paE18MrHcwf0NZtBX7BjLyNoBaXIN8eskNbAbrj/9LFeOC3U75qGxhdCMG5td10ipPsCZtG8hADsitv/dmuXBPzf9Vl68mM+Sdmtko7+gbq21XXwhp250tKsNkrupYm61RdH9ErxIpLao8NDMPJYQpIFl4oc4gitkrkJnviph9ltEGDnwJdMHKuuKuRQcNWPSlhze5JlkiLem+/4yaIB3dH3uI087mrvH5dfFo9V8eLyzKS37xZ5DzFBRDPv1VYck4ckpy/Lh2YQB14/IWL7RrcI+1Ch2LPDymVZoRysoQxp840bhJh2DJDqeuDaFLKfSWKMDPibIa/vIJlR6U8YALdtX4CeNcV+bc8H4FUBCTcNBfto0XcWXeYZ49Zvmvj+wVmkooVwp5QxJOvLUEflsP8d44jN3JHTfzHJIx8nzzzBVjO4S+HVbj/fUQ/uu6OJ8WUuCTjsZpj5Ga4NFunCt6Bz6zjPzT9oWfMfhByA9rSu8/GAr4CD2SDmYRfDjvqLYQv0x5FgklRfkbTXjWa4QJaoLK6n73cuO13cBNyLo/zkAIzw=
  bucket: mhospitality
  skip_cleanup: true
  acl: public-read
  local-dir: travis-etl
  on:
    repo: sgioldasis/bigquery-etl-dataflow-sample
